perfomance enhancing drugs
Global-Chem/private-workers pull request #218
Opened 2023-07-21 17:31 UTC by Nickspizza001

2023-07-23 18:59 UTC, Sulstice requested changes

2023-07-23 18:59 UTC, Sulstice commented on machine_learning_operations/performance_enhancements/smiles_generator.py
> +    input_file = pd.read_csv('.\chemical_list.csv', header=None, usecols=[0], names=["smiles"])
are you sure that is right?

2023-07-23 19:11 UTC, Nickspizza001 reviewed
Approve

2023-07-23 19:11 UTC, Nickspizza001 commented on machine_learning_operations/performance_enhancements/smiles_generator.py
> +    input_file = pd.read_csv('.\chemical_list.csv', header=None, usecols=[0], names=["smiles"])
No, I will fix it immediately.

2023-07-26 14:47 UTC, solarwaffles approved these changes

2023-07-27 14:05 UTC, Sulstice approved these changes

2023-07-27 14:05 UTC, merged